export interface QuestionData {
  id?: string;
  section: string;
  sectionName: string;
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: string;
  marks?: number;
  negativeMarks?: number;
  difficulty?: string;
}

export const initialQuestions: QuestionData[] = [
  // ── SECTION 1: Communication & Customer Handling (5 Qs) ──
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: 'A customer visits the bank and says, "I don\'t want to buy any insurance. I have come only for my banking work." What would be the best response?',
    optionA: "You must listen to me before leaving.",
    optionB: "Insurance is compulsory with banking services.",
    optionC: "Certainly. Let me first help you with your banking requirement. If appropriate, I can later explain some relevant protection options.",
    optionD: "Then you should speak to someone else.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "A customer is upset because their insurance policy document has not been received. What should you do first?",
    optionA: "Tell them to contact the insurance company.",
    optionB: "Listen to the concern, check the status and guide the customer on the next step.",
    optionC: "Tell them that such delays are normal.",
    optionD: "Ignore the complaint until the customer follows up again.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "Which approach is most appropriate when speaking to a senior bank customer?",
    optionA: "Use technical terminology to demonstrate knowledge.",
    optionB: "Speak quickly and focus on completing the sale.",
    optionC: "Understand the customer's needs and explain the product in simple language.",
    optionD: "Give the customer all product brochures and ask them to decide.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: 'A customer says, "I already have insurance through my employer." What is the best response?',
    optionA: "Your employer insurance is not useful.",
    optionB: "You don't need another policy.",
    optionC: "That's good to know. May I understand what your current coverage is so we can see whether there are any additional needs?",
    optionD: "You should immediately buy our policy.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "When a customer expresses doubt about an insurance product's claims process, how should an ARM respond?",
    optionA: "Assure them that claims are handled automatically without paperwork.",
    optionB: "Acknowledge their concern, explain the hassle-free claim settlement ratio, and walk them through the transparent procedure.",
    optionC: "Tell them claims are the insurance company's job, not the bank's.",
    optionD: "Change the topic to interest rates.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },

  // ── SECTION 2: Basic English (5 Qs) ──
  {
    section: "english",
    sectionName: "Basic English",
    question: "Choose the correct sentence:",
    optionA: "The customer have submitted the documents.",
    optionB: "The customer has submitted the documents.",
    optionC: "The customer having submitted documents.",
    optionD: "The customer submit the documents.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Choose the appropriate word: "We need to ______ the customer\'s requirements before suggesting a product."',
    optionA: "understand",
    optionB: "understood",
    optionC: "understanding",
    optionD: "understands",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'What does "eligible" mean?',
    optionA: "Interested",
    optionB: "Qualified to receive or apply for something",
    optionC: "Expensive",
    optionD: "Mandatory",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: "Which is the most professional opening for a customer conversation?",
    optionA: "What do you want?",
    optionB: "Tell me your requirement quickly.",
    optionC: "Good morning, Sir/Ma'am. How may I assist you today?",
    optionD: "You have been selected for an offer.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Select the synonym for "Confidential":',
    optionA: "Public",
    optionB: "Secret or private",
    optionC: "Optional",
    optionD: "Complicated",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },

  // ── SECTION 3: Mental Ability & Reasoning (5 Qs) ──
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Find the next number: 3, 6, 12, 24, ?",
    optionA: "36",
    optionB: "42",
    optionC: "48",
    optionD: "54",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "If BANK is coded as CBOL, how would LOAN be coded?",
    optionA: "MPBO",
    optionB: "MPAO",
    optionC: "LPBO",
    optionD: "NQCP",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Ravi is older than Amit. Amit is older than Karan. Who is the youngest?",
    optionA: "Ravi",
    optionB: "Amit",
    optionC: "Karan",
    optionD: "Cannot say",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "A customer is standing facing East. He turns left and then left again. Which direction is he facing?",
    optionA: "North",
    optionB: "South",
    optionC: "East",
    optionD: "West",
    correctAnswer: "D",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Find the odd one out: Deposit, Withdrawal, Loan, Chequebook, Banana",
    optionA: "Deposit",
    optionB: "Loan",
    optionC: "Banana",
    optionD: "Withdrawal",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },

  // ── SECTION 4: Basic Maths & Numerical Ability (5 Qs) ──
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A customer invests ₹50,000 and earns a return of 10%. What is the return?",
    optionA: "₹2,500",
    optionB: "₹5,000",
    optionC: "₹7,500",
    optionD: "₹10,000",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A product has an annual premium of ₹24,000. What is the approximate monthly equivalent?",
    optionA: "₹1,500",
    optionB: "₹2,000",
    optionC: "₹2,500",
    optionD: "₹3,000",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "An RM meets 40 customers and 10 purchase a product. What is the conversion rate?",
    optionA: "20%",
    optionB: "25%",
    optionC: "30%",
    optionD: "40%",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A customer's monthly income is ₹50,000. If 20% is allocated towards savings, how much is saved?",
    optionA: "₹5,000",
    optionB: "₹8,000",
    optionC: "₹10,000",
    optionD: "₹12,000",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A bank branch has 200 eligible customers. If 15% respond positively to an offer, approximately how many customers respond?",
    optionA: "15",
    optionB: "20",
    optionC: "30",
    optionD: "40",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },

  // ── SECTION 5: Banking & Financial Awareness (5 Qs) ──
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is the primary purpose of a savings bank account?",
    optionA: "To provide insurance",
    optionB: "To safely deposit money and facilitate transactions while earning applicable interest",
    optionC: "To provide loans automatically",
    optionD: "To invest only in shares",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What does EMI generally stand for?",
    optionA: "Equated Monthly Instalment",
    optionB: "Estimated Monthly Income",
    optionC: "Equity Market Investment",
    optionD: "Equal Money Interest",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is the main purpose of a credit score?",
    optionA: "To determine a person's age",
    optionB: "To indicate creditworthiness based on credit history",
    optionC: "To calculate salary",
    optionD: "To determine insurance premium only",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is the primary purpose of life insurance?",
    optionA: "To provide financial protection against specified life-related risks",
    optionB: "To provide free banking services",
    optionC: "To guarantee stock market returns",
    optionD: "To reduce income tax in every situation",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is health insurance primarily designed to provide?",
    optionA: "Protection against eligible healthcare expenses",
    optionB: "Guaranteed investment returns",
    optionC: "Monthly salary",
    optionD: "Free banking transactions",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },

  // ── SECTION 6: Sales Orientation & Situational Judgement (5 Qs) ──
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "You have been given a list of 20 customers to contact. You reach out to 15 but only two show interest. What would you do?",
    optionA: "Stop calling customers.",
    optionB: "Ask for a different list.",
    optionC: "Understand why customers are not responding and improve your approach.",
    optionD: "Wait for customers to contact you.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: 'A customer says: "I don\'t want insurance. It is too expensive." What would you do?',
    optionA: "Tell them they are wrong.",
    optionB: "Immediately offer the cheapest policy.",
    optionC: "Understand their needs and budget before explaining suitable options.",
    optionD: "End the conversation.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "Your manager gives you a monthly sales target. How do you respond?",
    optionA: "I don't like targets.",
    optionB: "I will try, but targets are not my responsibility.",
    optionC: "I will understand the target, break it into smaller activities and work towards achieving it.",
    optionD: "I will ask someone else to help me achieve it.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: 'A customer is interested but says, "I need some time to think." What is the best approach?',
    optionA: "Pressure them to purchase immediately.",
    optionB: "Ask what information they need and offer to clarify their concerns.",
    optionC: "Tell them the offer will disappear immediately.",
    optionD: "End the conversation.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "You are unable to answer a customer's technical question. What should you do?",
    optionA: "Give an answer anyway.",
    optionB: "Avoid the question.",
    optionC: "Tell the customer you will verify the information and come back with the correct answer.",
    optionD: "Ask the customer to search online.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
];
