export interface QuestionData {
  id?: string;
  section: string;
  sectionName: string;
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: string;
  marks?: number;
  negativeMarks?: number;
  difficulty?: string;
}

export const initialQuestions: QuestionData[] = [
  // SECTION 1: Communication & Customer Handling (10 Qs)
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: 'A customer visits the bank and says, "I don\'t want to buy any insurance. I have come only for my banking work." What would be the best response?',
    optionA: "You must listen to me before leaving.",
    optionB: "Insurance is compulsory with banking services.",
    optionC: "Certainly. Let me first help you with your banking requirement. If appropriate, I can later explain some relevant protection options.",
    optionD: "Then you should speak to someone else.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "A customer is upset because their insurance policy document has not been received. What should you do first?",
    optionA: "Tell them to contact the insurance company.",
    optionB: "Listen to the concern, check the status and guide the customer on the next step.",
    optionC: "Tell them that such delays are normal.",
    optionD: "Ignore the complaint until the customer follows up again.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "Which approach is most appropriate when speaking to a senior bank customer?",
    optionA: "Use technical terminology to demonstrate knowledge.",
    optionB: "Speak quickly and focus on completing the sale.",
    optionC: "Understand the customer's needs and explain the product in simple language.",
    optionD: "Give the customer all product brochures and ask them to decide.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: 'A customer says, "I already have insurance through my employer." What is the best response?',
    optionA: "Your employer insurance is not useful.",
    optionB: "You don't need another policy.",
    optionC: "That's good to know. May I understand what your current coverage is so we can see whether there are any additional needs?",
    optionD: "You should immediately buy our policy.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "When a customer expresses doubt about an insurance product's claims process, how should an ARM respond?",
    optionA: "Assure them that claims are handled automatically without paperwork.",
    optionB: "Acknowledge their concern, explain the hassle-free claim settlement ratio, and walk them through the transparent procedure.",
    optionC: "Tell them claims are the insurance company's job, not the bank's.",
    optionD: "Change the topic to interest rates.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "What is active listening in customer relationship management?",
    optionA: "Nodding silently while thinking of the sales pitch.",
    optionB: "Interrupting the customer to save time.",
    optionC: "Focusing completely on the customer's words, asking clarifying questions, and summarizing their requirement.",
    optionD: "Writing down notes without looking at the customer.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "A high-net-worth customer asks for details about estate protection. You aren't fully sure of the tax intricacies. What should you do?",
    optionA: "Guess the tax savings to make a good impression.",
    optionB: "Politely inform the customer you will consult your senior specialist and provide precise verified information.",
    optionC: "Advise them to consult a external lawyer immediately.",
    optionD: "Refuse to discuss the topic.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "How should an ARM handle a customer who is angry due to a long waiting queue at the bank?",
    optionA: "Blame the branch manager for staff shortage.",
    optionB: "Calmly greet the customer, empathize with their time constraints, and assist them efficiently.",
    optionC: "Ask the security guard to escort the customer outside.",
    optionD: "Tell the customer to come back tomorrow.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "Which body language sign indicates that a customer is engaged and open to communication?",
    optionA: "Crossed arms and looking away at the door.",
    optionB: "Leaning slightly forward, maintaining eye contact, and nodding.",
    optionC: "Checking watch repeatedly.",
    optionD: "Tapping fingers impatiently on the desk.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "communication",
    sectionName: "Communication & Customer Handling",
    question: "What is the primary objective of follow-up communication after a customer buys a financial solution?",
    optionA: "To sell another product immediately.",
    optionB: "To confirm satisfaction, assist with policy delivery, and build long-term trust.",
    optionC: "To complete bank attendance requirements.",
    optionD: "To ask for family contact numbers right away.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },

  // SECTION 2: Basic English (10 Qs)
  {
    section: "english",
    sectionName: "Basic English",
    question: "Choose the correct sentence:",
    optionA: "The customer have submitted the documents.",
    optionB: "The customer has submitted the documents.",
    optionC: "The customer having submitted documents.",
    optionD: "The customer submit the documents.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Choose the appropriate word: "We need to ______ the customer\'s requirements before suggesting a product."',
    optionA: "understand",
    optionB: "understood",
    optionC: "understanding",
    optionD: "understands",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'What does "eligible" mean?',
    optionA: "Interested",
    optionB: "Qualified to receive or apply for something",
    optionC: "Expensive",
    optionD: "Mandatory",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: "Which is the most professional opening for a customer conversation?",
    optionA: "What do you want?",
    optionB: "Tell me your requirement quickly.",
    optionC: "Good morning, Sir/Ma'am. How may I assist you today?",
    optionD: "You have been selected for an offer.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Select the synonym for "Confidential":',
    optionA: "Public",
    optionB: "Secret or private",
    optionC: "Optional",
    optionD: "Complicated",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Fill in the blank: "All branch employees must adhere ______ the security guidelines."',
    optionA: "with",
    optionB: "to",
    optionC: "for",
    optionD: "on",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Identify the antonym of "Transparent":',
    optionA: "Clear",
    optionB: "Opaque / Hidden",
    optionC: "Honest",
    optionD: "Simple",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: "Choose the correctly spelled word:",
    optionA: "Accommodation",
    optionB: "Acomodation",
    optionC: "Accomodation",
    optionD: "Acommodation",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Choose the correct preposition: "The portfolio manager will meet the client ______ 3:00 PM."',
    optionA: "at",
    optionB: "on",
    optionC: "in",
    optionD: "by",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "english",
    sectionName: "Basic English",
    question: 'Complete the phrase: "In order to streamline operations, we must reduce ______ paperwork."',
    optionA: "unnecessary",
    optionB: "unnecessaryness",
    optionC: "unnecessity",
    optionD: "unneccessary",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },

  // SECTION 3: Mental Ability & Reasoning (10 Qs)
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Find the next number: 3, 6, 12, 24, ?",
    optionA: "36",
    optionB: "42",
    optionC: "48",
    optionD: "54",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "If BANK is coded as CBOL, how would LOAN be coded?",
    optionA: "MPBO",
    optionB: "MPAO",
    optionC: "LPBO",
    optionD: "NQCP",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Ravi is older than Amit. Amit is older than Karan. Who is the youngest?",
    optionA: "Ravi",
    optionB: "Amit",
    optionC: "Karan",
    optionD: "Cannot say",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "A customer is standing facing East. He turns left and then left again. Which direction is he facing?",
    optionA: "North",
    optionB: "South",
    optionC: "East",
    optionD: "West",
    correctAnswer: "D",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Find the odd one out: Deposit, Withdrawal, Loan, Chequebook, Banana",
    optionA: "Deposit",
    optionB: "Loan",
    optionC: "Banana",
    optionD: "Withdrawal",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Complete the series: A, C, E, G, ?",
    optionA: "H",
    optionB: "I",
    optionC: "J",
    optionD: "K",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Pointing to a photograph, Priya said, 'He is the son of my grandfather's only son.' How is the person related to Priya?",
    optionA: "Brother",
    optionB: "Father",
    optionC: "Uncle",
    optionD: "Cousin",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "All banks have vaults. Vault X is in Branch Y. Therefore:",
    optionA: "Branch Y is a bank branch with a vault.",
    optionB: "Vault X has no security.",
    optionC: "All branches are named Y.",
    optionD: "Branch Y has no customer desk.",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "If 5 relationship managers take 5 hours to serve 25 clients, how long will 10 RMs take to serve 50 clients at the same speed?",
    optionA: "2.5 hours",
    optionB: "5 hours",
    optionC: "10 hours",
    optionD: "12.5 hours",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "reasoning",
    sectionName: "Mental Ability & Reasoning",
    question: "Find the missing letter in the pattern: B, D, G, K, ?",
    optionA: "N",
    optionB: "O",
    optionC: "P",
    optionD: "Q",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Hard",
  },

  // SECTION 4: Basic Maths & Numerical Ability (10 Qs)
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A customer invests ₹50,000 and earns a return of 10%. What is the return?",
    optionA: "₹2,500",
    optionB: "₹5,000",
    optionC: "₹7,500",
    optionD: "₹10,000",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A product has an annual premium of ₹24,000. What is the approximate monthly equivalent?",
    optionA: "₹1,500",
    optionB: "₹2,000",
    optionC: "₹2,500",
    optionD: "₹3,000",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "An RM meets 40 customers and 10 purchase a product. What is the conversion rate?",
    optionA: "20%",
    optionB: "25%",
    optionC: "30%",
    optionD: "40%",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A customer's monthly income is ₹50,000. If 20% is allocated towards savings, how much is saved?",
    optionA: "₹5,000",
    optionB: "₹8,000",
    optionC: "₹10,000",
    optionD: "₹12,000",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A bank branch has 200 eligible customers. If 15% respond positively to an offer, approximately how many customers respond?",
    optionA: "15",
    optionB: "20",
    optionC: "30",
    optionD: "40",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "If a Fixed Deposit pays 6% annual simple interest, how much total interest will ₹1,00,000 earn in 3 years?",
    optionA: "₹12,000",
    optionB: "₹18,000",
    optionC: "₹20,000",
    optionD: "₹24,000",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "An insurance premium of ₹10,000 is given a 5% early payment discount. What is the final amount payable?",
    optionA: "₹9,000",
    optionB: "₹9,500",
    optionC: "₹9,800",
    optionD: "₹10,500",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "If an ARM achieves ₹3,00,000 in sales out of a target of ₹4,00,000, what is the achievement percentage?",
    optionA: "60%",
    optionB: "70%",
    optionC: "75%",
    optionD: "80%",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "A customer deposits ₹1,500 every month in a recurring deposit for 1 year. What is the total principal deposited?",
    optionA: "₹15,000",
    optionB: "₹16,500",
    optionC: "₹18,000",
    optionD: "₹20,000",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "maths",
    sectionName: "Basic Maths & Numerical Ability",
    question: "The ratio of savings accounts to current accounts opened in a branch is 3:2. If 150 savings accounts were opened, how many current accounts were opened?",
    optionA: "80",
    optionB: "100",
    optionC: "120",
    optionD: "150",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },

  // SECTION 5: Banking & Financial Awareness (10 Qs)
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is the primary purpose of a savings bank account?",
    optionA: "To provide insurance",
    optionB: "To safely deposit money and facilitate transactions while earning applicable interest",
    optionC: "To provide loans automatically",
    optionD: "To invest only in shares",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What does EMI generally stand for?",
    optionA: "Equated Monthly Instalment",
    optionB: "Estimated Monthly Income",
    optionC: "Equity Market Investment",
    optionD: "Equal Money Interest",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is the main purpose of a credit score?",
    optionA: "To determine a person's age",
    optionB: "To indicate creditworthiness based on credit history",
    optionC: "To calculate salary",
    optionD: "To determine insurance premium only",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is the primary purpose of life insurance?",
    optionA: "To provide financial protection against specified life-related risks",
    optionB: "To provide free banking services",
    optionC: "To guarantee stock market returns",
    optionD: "To reduce income tax in every situation",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is health insurance primarily designed to provide?",
    optionA: "Protection against eligible healthcare expenses",
    optionB: "Guaranteed investment returns",
    optionC: "Monthly salary",
    optionD: "Free banking transactions",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is a premium in insurance?",
    optionA: "The amount paid for insurance coverage",
    optionB: "The amount of a bank loan",
    optionC: "The customer's salary",
    optionD: "A bank transaction fee",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is diversification?",
    optionA: "Putting all money into one investment",
    optionB: "Spreading investments across different assets to manage risk",
    optionC: "Avoiding all investments",
    optionD: "Borrowing money from multiple banks",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What does KYC stand for in banking?",
    optionA: "Know Your Customer",
    optionB: "Keep Your Cash",
    optionC: "Know Your Credit",
    optionD: "Key Yield Calculation",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "Which central bank regulates banking operations in India?",
    optionA: "State Bank of India (SBI)",
    optionB: "Reserve Bank of India (RBI)",
    optionC: "NABARD",
    optionD: "SEBI",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "banking",
    sectionName: "Banking & Financial Awareness",
    question: "What is Bancassurance?",
    optionA: "A partnership between a bank and an insurance company to distribute insurance products to bank customers",
    optionB: "An international banking loan facility",
    optionC: "A type of ATM card",
    optionD: "Insurance exclusively for bank buildings",
    correctAnswer: "A",
    marks: 1,
    difficulty: "Medium",
  },

  // SECTION 6: Sales Orientation & Situational Judgement (10 Qs)
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "You have been given a list of 20 customers to contact. You reach out to 15 but only two show interest. What would you do?",
    optionA: "Stop calling customers.",
    optionB: "Ask for a different list.",
    optionC: "Understand why customers are not responding and improve your approach.",
    optionD: "Wait for customers to contact you.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: 'A customer says: "I don\'t want insurance. It is too expensive." What would you do?',
    optionA: "Tell them they are wrong.",
    optionB: "Immediately offer the cheapest policy.",
    optionC: "Understand their needs and budget before explaining suitable options.",
    optionD: "End the conversation.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "Your manager gives you a monthly sales target. How do you respond?",
    optionA: "I don't like targets.",
    optionB: "I will try, but targets are not my responsibility.",
    optionC: "I will understand the target, break it into smaller activities and work towards achieving it.",
    optionD: "I will ask someone else to help me achieve it.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: 'A customer is interested but says, "I need some time to think." What is the best approach?',
    optionA: "Pressure them to purchase immediately.",
    optionB: "Ask what information they need and offer to clarify their concerns.",
    optionC: "Tell them the offer will disappear immediately.",
    optionD: "End the conversation.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "You are unable to answer a customer's technical question. What should you do?",
    optionA: "Give an answer anyway.",
    optionB: "Avoid the question.",
    optionC: "Tell the customer you will verify the information and come back with the correct answer.",
    optionD: "Ask the customer to search online.",
    correctAnswer: "C",
    marks: 1,
    difficulty: "Easy",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "A bank walk-in customer wants to open a Fixed Deposit of ₹5 Lakhs for 3 years. You notice he has a young family. What cross-selling opportunity should you explore?",
    optionA: "Force him to cancel the FD and buy life insurance.",
    optionB: "Complete the FD first, then ask open-ended questions about family protection and health coverage.",
    optionC: "Tell him FDs are bad investments.",
    optionD: "Say nothing and send him away.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Hard",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "When meeting a prospect who had a bad experience with another financial institution, what is your best pitch strategy?",
    optionA: "Criticize the competitor heavily.",
    optionB: "Listen patiently to their dissatisfaction, show empathy, and explain your bank's transparent service commitment.",
    optionC: "Disregard their story.",
    optionD: "Promise 100% returns guaranteed.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "What is the key driver of long-term sales success in a Banca Channel environment?",
    optionA: "Aggressive pushing regardless of customer need.",
    optionB: "Building trust, understanding customer financial goals, and ethical recommendation.",
    optionC: "Making 100 random phone calls daily.",
    optionD: "Only talking to wealthy clients.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "If a customer agrees to buy a policy but backs out right before signing due to fear of paperwork, what should you do?",
    optionA: "Argue with the customer.",
    optionB: "Reassure them, offer step-by-step assistance with documentation, and simplify the onboarding process.",
    optionC: "Charge a cancellation fee.",
    optionD: "Complain to your manager.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
  {
    section: "sales",
    sectionName: "Sales Orientation & Situational Judgement",
    question: "How do top-performing Assistant Relationship Managers structure their daily routine?",
    optionA: "Wait for walk-in customers all day without planning.",
    optionB: "Plan customer appointments in advance, prepare product briefs, align branch leads, and review daily progress.",
    optionC: "Only work during audit weeks.",
    optionD: "Focus only on administrative paperwork.",
    correctAnswer: "B",
    marks: 1,
    difficulty: "Medium",
  },
];
